# Generated by Django 6.0 on 2025-12-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.CharField(blank=True, default='GLOBAL', max_length=20)),
                ('symbol', models.CharField(blank=True, max_length=50)),
                ('accuracy_rating', models.IntegerField(default=0)),
                ('ux_rating', models.IntegerField(default=0)),
                ('speed_rating', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True)),
                ('hallucination_report', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.CharField(max_length=50)),
                ('market', models.CharField(choices=[('EQUITY', 'Equity'), ('FUTURES', 'Futures'), ('OPTIONS', 'Options'), ('CRYPTO', 'Crypto'), ('FOREX', 'Forex'), ('METALS', 'Metals')], max_length=20)),
                ('trade_type', models.CharField(max_length=20)),
                ('model_probability', models.FloatField()),
                ('predicted_direction', models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down'), ('FLAT', 'Flat')], max_length=10)),
                ('entry_price', models.FloatField()),
                ('target_price', models.FloatField()),
                ('stop_loss_price', models.FloatField()),
                ('actual_outcome', models.CharField(choices=[('PENDING', 'Pending'), ('WIN', 'Win'), ('LOSS', 'Loss'), ('BREAKEVEN', 'Breakeven')], default='PENDING', max_length=10)),
                ('pnl_percent', models.FloatField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
