# Generated by Django 6.0 on 2025-12-16 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_subscription_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('bias', models.CharField(max_length=10)),
                ('entry_price', models.FloatField()),
                ('stop_loss', models.FloatField()),
                ('target', models.FloatField()),
                ('confidence', models.FloatField(default=0.0)),
                ('leverage', models.CharField(default='Low', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('WIN', 'Win'), ('LOSS', 'Loss'), ('BREAKEVEN', 'Breakeven')], default='PENDING', max_length=20)),
                ('pnl_percent', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
