# Generated by Django 5.2.9 on 2026-01-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_journalentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='razorpay_subscription_id',
            new_name='lemon_squeezy_customer_id',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='subscription_end_date',
            new_name='renews_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='trial_start_date',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lemon_squeezy_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='update_payment_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subscription_status',
            field=models.CharField(default='inactive', max_length=50),
        ),
    ]
