# Generated by Django 5.2.9 on 2026-01-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_razorpay_subscription_id_userprofile_lemon_squeezy_customer_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PredictionLog',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='renews_at',
            new_name='last_verified_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lemon_squeezy_customer_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lemon_squeezy_subscription_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='subscription_status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='update_payment_url',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gumroad_license_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='terms_accepted',
            field=models.BooleanField(default=True),
        ),
    ]
